---
abstract: 'Template::Toolkit plugin to make MARC friendly'
author:
  - 'Jared Camins-Esakov <jcamins@cpbibliography.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: gpl_3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-MARC
no_index:
  directory:
    - t
    - inc
requires:
  MARC::Record: 2
  Template: 2.22
version: 0.02
